[build]
  command = "cd nextjs && npm install && npm run build"
  publish = "nextjs/.next"
  environment = { NEXT_TELEMETRY_DISABLED = "1" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["styled-jsx"]

[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://limghfdolwgimptrxpcr.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_aG5g0hLBTHjFN40xHVRKBg_roPgXy6L"
